In [3]:
import numpy as np
import pandas as pd

In [4]:
series = pdf.Series(np.random.rand(34)) #create random values in range of 34

NameError: name 'pdf' is not defined

In [5]:
series = pd.Series(np.random.rand(34)) #create random values in range of 34

In [6]:
series

0     0.759278
1     0.616987
2     0.228321
3     0.971469
4     0.267766
5     0.938189
6     0.397705
7     0.484584
8     0.327815
9     0.974034
10    0.412746
11    0.076629
12    0.535699
13    0.798912
14    0.059481
15    0.278101
16    0.518061
17    0.694823
18    0.676459
19    0.766635
20    0.718392
21    0.298176
22    0.312050
23    0.768499
24    0.146087
25    0.925830
26    0.716664
27    0.866094
28    0.990605
29    0.602924
30    0.433533
31    0.412024
32    0.056463
33    0.114770
dtype: float64

In [7]:
series = pd.Series(np.random.rand(34,5))

ValueError: Data must be 1-dimensional

In [8]:
series = pd.Series(np.random.rand(34),index.arange(34)

SyntaxError: incomplete input (387286533.py, line 1)

In [9]:
series = pd.DataFrame(np.random.rand(34,5),index.arange(34))

NameError: name 'index' is not defined

In [10]:
clear

In [11]:
series = pd.DataFrame(np.random.rand(34,5),index=arange(34))

NameError: name 'arange' is not defined

In [12]:
series = pd.DataFrame(np.random.rand(34,5),index=np.arange(34))

In [13]:
series

           0         1         2         3         4
0   0.869177  0.234147  0.940064  0.473970  0.361014
1   0.596677  0.471264  0.495854  0.551522  0.694410
2   0.756749  0.558490  0.846293  0.129766  0.919949
3   0.210793  0.716203  0.038546  0.607009  0.902327
4   0.339294  0.538599  0.523121  0.885758  0.142123
5   0.460647  0.898446  0.007545  0.987025  0.624142
6   0.577653  0.979119  0.108100  0.048454  0.146473
7   0.320289  0.829956  0.995263  0.041897  0.146254
8   0.449955  0.469306  0.255272  0.711340  0.160879
9   0.950387  0.679783  0.841071  0.831338  0.961992
10  0.725516  0.188703  0.870835  0.657401  0.017196
11  0.787015  0.738428  0.417626  0.926075  0.276640
12  0.732767  0.524694  0.280194  0.306880  0.521751
13  0.633629  0.316157  0.591561  0.472270  0.186463
14  0.511544  0.858379  0.483580  0.995105  0.688325
15  0.695041  0.833316  0.638896  0.714002  0.531689
16  0.344799  0.354411  0.836991  0.825366  0.496820
17  0.394769  0.365707  0.360940  0.312639  0.221639
18  0.910403  0.435730  0.808163  0.010796  0.893741
19  0.803225  0.093240  0.200333  0.954408  0.203457
20  0.632405  0.376669  0.772344  0.957008  0.544798
21  0.175304  0.636215  0.602807  0.175947  0.561938
22  0.742282  0.880899  0.115423  0.922307  0.530991
23  0.149430  0.879813  0.218052  0.284823  0.069834
24  0.476302  0.541652  0.339718  0.199430  0.603206
25  0.249612  0.338399  0.022877  0.223118  0.658511
26  0.520299  0.003608  0.239881  0.142283  0.765254
27  0.963151  0.120603  0.524489  0.514812  0.145686
28  0.973810  0.657881  0.876997  0.842475  0.103630
29  0.057908  0.497896  0.707752  0.837767  0.727304
30  0.149762  0.680770  0.904787  0.616192  0.588927
31  0.032802  0.364418  0.106371  0.562966  0.942107
32  0.277075  0.347983  0.324413  0.267280  0.615786
33  0.631028  0.289144  0.901380  0.744782  0.305532

In [14]:
series.sort_index(axis=0)

           0         1         2         3         4
0   0.869177  0.234147  0.940064  0.473970  0.361014
1   0.596677  0.471264  0.495854  0.551522  0.694410
2   0.756749  0.558490  0.846293  0.129766  0.919949
3   0.210793  0.716203  0.038546  0.607009  0.902327
4   0.339294  0.538599  0.523121  0.885758  0.142123
5   0.460647  0.898446  0.007545  0.987025  0.624142
6   0.577653  0.979119  0.108100  0.048454  0.146473
7   0.320289  0.829956  0.995263  0.041897  0.146254
8   0.449955  0.469306  0.255272  0.711340  0.160879
9   0.950387  0.679783  0.841071  0.831338  0.961992
10  0.725516  0.188703  0.870835  0.657401  0.017196
11  0.787015  0.738428  0.417626  0.926075  0.276640
12  0.732767  0.524694  0.280194  0.306880  0.521751
13  0.633629  0.316157  0.591561  0.472270  0.186463
14  0.511544  0.858379  0.483580  0.995105  0.688325
15  0.695041  0.833316  0.638896  0.714002  0.531689
16  0.344799  0.354411  0.836991  0.825366  0.496820
17  0.394769  0.365707  0.360940  0.312639  0.221639
18  0.910403  0.435730  0.808163  0.010796  0.893741
19  0.803225  0.093240  0.200333  0.954408  0.203457
20  0.632405  0.376669  0.772344  0.957008  0.544798
21  0.175304  0.636215  0.602807  0.175947  0.561938
22  0.742282  0.880899  0.115423  0.922307  0.530991
23  0.149430  0.879813  0.218052  0.284823  0.069834
24  0.476302  0.541652  0.339718  0.199430  0.603206
25  0.249612  0.338399  0.022877  0.223118  0.658511
26  0.520299  0.003608  0.239881  0.142283  0.765254
27  0.963151  0.120603  0.524489  0.514812  0.145686
28  0.973810  0.657881  0.876997  0.842475  0.103630
29  0.057908  0.497896  0.707752  0.837767  0.727304
30  0.149762  0.680770  0.904787  0.616192  0.588927
31  0.032802  0.364418  0.106371  0.562966  0.942107
32  0.277075  0.347983  0.324413  0.267280  0.615786
33  0.631028  0.289144  0.901380  0.744782  0.305532

In [15]:
type(series)

pandas.core.frame.DataFrame

In [16]:
type(series[0])

pandas.core.series.Series

In [17]:
newDF.columns

NameError: name 'newDF' is not defined

In [18]:
series.columns

RangeIndex(start=0, stop=5, step=1)

In [19]:
series.columns = list('ABCDE')

In [20]:
series.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [21]:
series

           A         B         C         D         E
0   0.869177  0.234147  0.940064  0.473970  0.361014
1   0.596677  0.471264  0.495854  0.551522  0.694410
2   0.756749  0.558490  0.846293  0.129766  0.919949
3   0.210793  0.716203  0.038546  0.607009  0.902327
4   0.339294  0.538599  0.523121  0.885758  0.142123
5   0.460647  0.898446  0.007545  0.987025  0.624142
6   0.577653  0.979119  0.108100  0.048454  0.146473
7   0.320289  0.829956  0.995263  0.041897  0.146254
8   0.449955  0.469306  0.255272  0.711340  0.160879
9   0.950387  0.679783  0.841071  0.831338  0.961992
10  0.725516  0.188703  0.870835  0.657401  0.017196
11  0.787015  0.738428  0.417626  0.926075  0.276640
12  0.732767  0.524694  0.280194  0.306880  0.521751
13  0.633629  0.316157  0.591561  0.472270  0.186463
14  0.511544  0.858379  0.483580  0.995105  0.688325
15  0.695041  0.833316  0.638896  0.714002  0.531689
16  0.344799  0.354411  0.836991  0.825366  0.496820
17  0.394769  0.365707  0.360940  0.312639  0.221639
18  0.910403  0.435730  0.808163  0.010796  0.893741
19  0.803225  0.093240  0.200333  0.954408  0.203457
20  0.632405  0.376669  0.772344  0.957008  0.544798
21  0.175304  0.636215  0.602807  0.175947  0.561938
22  0.742282  0.880899  0.115423  0.922307  0.530991
23  0.149430  0.879813  0.218052  0.284823  0.069834
24  0.476302  0.541652  0.339718  0.199430  0.603206
25  0.249612  0.338399  0.022877  0.223118  0.658511
26  0.520299  0.003608  0.239881  0.142283  0.765254
27  0.963151  0.120603  0.524489  0.514812  0.145686
28  0.973810  0.657881  0.876997  0.842475  0.103630
29  0.057908  0.497896  0.707752  0.837767  0.727304
30  0.149762  0.680770  0.904787  0.616192  0.588927
31  0.032802  0.364418  0.106371  0.562966  0.942107
32  0.277075  0.347983  0.324413  0.267280  0.615786
33  0.631028  0.289144  0.901380  0.744782  0.305532

In [22]:
series.columns = list([0])

ValueError: Length mismatch: Expected axis has 5 elements, new values have 1 elements

In [23]:
series.loc[0,'A'] = 65

In [24]:
series

            A         B         C         D         E
0   65.000000  0.234147  0.940064  0.473970  0.361014
1    0.596677  0.471264  0.495854  0.551522  0.694410
2    0.756749  0.558490  0.846293  0.129766  0.919949
3    0.210793  0.716203  0.038546  0.607009  0.902327
4    0.339294  0.538599  0.523121  0.885758  0.142123
5    0.460647  0.898446  0.007545  0.987025  0.624142
6    0.577653  0.979119  0.108100  0.048454  0.146473
7    0.320289  0.829956  0.995263  0.041897  0.146254
8    0.449955  0.469306  0.255272  0.711340  0.160879
9    0.950387  0.679783  0.841071  0.831338  0.961992
10   0.725516  0.188703  0.870835  0.657401  0.017196
11   0.787015  0.738428  0.417626  0.926075  0.276640
12   0.732767  0.524694  0.280194  0.306880  0.521751
13   0.633629  0.316157  0.591561  0.472270  0.186463
14   0.511544  0.858379  0.483580  0.995105  0.688325
15   0.695041  0.833316  0.638896  0.714002  0.531689
16   0.344799  0.354411  0.836991  0.825366  0.496820
17   0.394769  0.365707  0.360940  0.312639  0.221639
18   0.910403  0.435730  0.808163  0.010796  0.893741
19   0.803225  0.093240  0.200333  0.954408  0.203457
20   0.632405  0.376669  0.772344  0.957008  0.544798
21   0.175304  0.636215  0.602807  0.175947  0.561938
22   0.742282  0.880899  0.115423  0.922307  0.530991
23   0.149430  0.879813  0.218052  0.284823  0.069834
24   0.476302  0.541652  0.339718  0.199430  0.603206
25   0.249612  0.338399  0.022877  0.223118  0.658511
26   0.520299  0.003608  0.239881  0.142283  0.765254
27   0.963151  0.120603  0.524489  0.514812  0.145686
28   0.973810  0.657881  0.876997  0.842475  0.103630
29   0.057908  0.497896  0.707752  0.837767  0.727304
30   0.149762  0.680770  0.904787  0.616192  0.588927
31   0.032802  0.364418  0.106371  0.562966  0.942107
32   0.277075  0.347983  0.324413  0.267280  0.615786
33   0.631028  0.289144  0.901380  0.744782  0.305532

In [25]:
series.loc[0,0] = 65

In [26]:
series

            A         B         C         D         E     0
0   65.000000  0.234147  0.940064  0.473970  0.361014  65.0
1    0.596677  0.471264  0.495854  0.551522  0.694410   NaN
2    0.756749  0.558490  0.846293  0.129766  0.919949   NaN
3    0.210793  0.716203  0.038546  0.607009  0.902327   NaN
4    0.339294  0.538599  0.523121  0.885758  0.142123   NaN
5    0.460647  0.898446  0.007545  0.987025  0.624142   NaN
6    0.577653  0.979119  0.108100  0.048454  0.146473   NaN
7    0.320289  0.829956  0.995263  0.041897  0.146254   NaN
8    0.449955  0.469306  0.255272  0.711340  0.160879   NaN
9    0.950387  0.679783  0.841071  0.831338  0.961992   NaN
10   0.725516  0.188703  0.870835  0.657401  0.017196   NaN
11   0.787015  0.738428  0.417626  0.926075  0.276640   NaN
12   0.732767  0.524694  0.280194  0.306880  0.521751   NaN
13   0.633629  0.316157  0.591561  0.472270  0.186463   NaN
14   0.511544  0.858379  0.483580  0.995105  0.688325   NaN
15   0.695041  0.833316  0.638896  0.714002  0.531689   NaN
16   0.344799  0.354411  0.836991  0.825366  0.496820   NaN
17   0.394769  0.365707  0.360940  0.312639  0.221639   NaN
18   0.910403  0.435730  0.808163  0.010796  0.893741   NaN
19   0.803225  0.093240  0.200333  0.954408  0.203457   NaN
20   0.632405  0.376669  0.772344  0.957008  0.544798   NaN
21   0.175304  0.636215  0.602807  0.175947  0.561938   NaN
22   0.742282  0.880899  0.115423  0.922307  0.530991   NaN
23   0.149430  0.879813  0.218052  0.284823  0.069834   NaN
24   0.476302  0.541652  0.339718  0.199430  0.603206   NaN
25   0.249612  0.338399  0.022877  0.223118  0.658511   NaN
26   0.520299  0.003608  0.239881  0.142283  0.765254   NaN
27   0.963151  0.120603  0.524489  0.514812  0.145686   NaN
28   0.973810  0.657881  0.876997  0.842475  0.103630   NaN
29   0.057908  0.497896  0.707752  0.837767  0.727304   NaN
30   0.149762  0.680770  0.904787  0.616192  0.588927   NaN
31   0.032802  0.364418  0.106371  0.562966  0.942107   NaN
32   0.277075  0.347983  0.324413  0.267280  0.615786   NaN
33   0.631028  0.289144  0.901380  0.744782  0.305532   NaN

In [27]:
series.drop(0, axis=1)

            A         B         C         D         E
0   65.000000  0.234147  0.940064  0.473970  0.361014
1    0.596677  0.471264  0.495854  0.551522  0.694410
2    0.756749  0.558490  0.846293  0.129766  0.919949
3    0.210793  0.716203  0.038546  0.607009  0.902327
4    0.339294  0.538599  0.523121  0.885758  0.142123
5    0.460647  0.898446  0.007545  0.987025  0.624142
6    0.577653  0.979119  0.108100  0.048454  0.146473
7    0.320289  0.829956  0.995263  0.041897  0.146254
8    0.449955  0.469306  0.255272  0.711340  0.160879
9    0.950387  0.679783  0.841071  0.831338  0.961992
10   0.725516  0.188703  0.870835  0.657401  0.017196
11   0.787015  0.738428  0.417626  0.926075  0.276640
12   0.732767  0.524694  0.280194  0.306880  0.521751
13   0.633629  0.316157  0.591561  0.472270  0.186463
14   0.511544  0.858379  0.483580  0.995105  0.688325
15   0.695041  0.833316  0.638896  0.714002  0.531689
16   0.344799  0.354411  0.836991  0.825366  0.496820
17   0.394769  0.365707  0.360940  0.312639  0.221639
18   0.910403  0.435730  0.808163  0.010796  0.893741
19   0.803225  0.093240  0.200333  0.954408  0.203457
20   0.632405  0.376669  0.772344  0.957008  0.544798
21   0.175304  0.636215  0.602807  0.175947  0.561938
22   0.742282  0.880899  0.115423  0.922307  0.530991
23   0.149430  0.879813  0.218052  0.284823  0.069834
24   0.476302  0.541652  0.339718  0.199430  0.603206
25   0.249612  0.338399  0.022877  0.223118  0.658511
26   0.520299  0.003608  0.239881  0.142283  0.765254
27   0.963151  0.120603  0.524489  0.514812  0.145686
28   0.973810  0.657881  0.876997  0.842475  0.103630
29   0.057908  0.497896  0.707752  0.837767  0.727304
30   0.149762  0.680770  0.904787  0.616192  0.588927
31   0.032802  0.364418  0.106371  0.562966  0.942107
32   0.277075  0.347983  0.324413  0.267280  0.615786
33   0.631028  0.289144  0.901380  0.744782  0.305532

In [28]:
series.loc([0],['A'])

TypeError: _LocationIndexer.__call__() takes from 1 to 2 positional arguments but 3 were given

In [29]:
series.loc[[0],['A']]

      A
0  65.0

In [30]:
series.loc[[0,1,2],['A','B']]

           A         B
0  65.000000  0.234147
1   0.596677  0.471264
2   0.756749  0.558490

In [31]:
series.iloc[0,'A']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [32]:
series.iloc[0,4]

0.36101422341524314

series.iloc[0,1]